### ISSUE TITLE
Problems running examples

### ISSUE THREAD

**Issue by egbulmer** [3b/cl-opengl#44] opened 2014-05-31 11:45 UTC
I am using SBCL (v1.1.17) and Windows 7. When I run the following in SLIME:

``` lisp
CL-USER> (ql:quickload "cl-opengl")
CL-USER> (ql:quickload "cl-glut-examples")
CL-USER> (cl-glut-examples:run-examples)
```

Most of the samples work fine but ... I do get errors for the `SHADER-VAO` demo:

``` lisp
  0: (CL-OPENGL-BINDINGS:CHECK-ERROR #<unavailable argument>)
  1: (CL-OPENGL-BINDINGS:GET-UNIFORM-LOCATION 3 #.(SB-SYS:INT-SAP #X01FA12E0))
  2: (CL-OPENGL:GET-UNIFORM-LOCATION 3 "angle")
  3: ((:METHOD CL-GLUT:TICK (CL-GLUT-EXAMPLES::SHADER-VAO-WINDOW)) #<CL-GLUT-EXAMPLES::SHADER-VAO-WINDOW {1004867CA3}>) [fast-method]
  4: ((LAMBDA (CL-GLUT:ID) :IN "C:/cygwin64/home/elliot/lisp/quicklisp/local-projects/cl-opengl/glut/interface.lisp") 132)
  5: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "C:/Users/Elliot/AppData/Local/common-lisp/cache/sbcl-1.1.17-win-x64/C/cygwin64/home/elliot/lisp/quicklisp/local-projects/cl-ope..
  6: ("foreign function: #x42CB8C")
  7: ("foreign function: #x403AD8")
  8: ("foreign function: #x200749F390")
  9: (CL-GLUT-EXAMPLES:RUN-EXAMPLES)
 10: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CL-GLUT-EXAMPLES:RUN-EXAMPLES) #<NULL-LEXENV>)
 11: (EVAL (CL-GLUT-EXAMPLES:RUN-EXAMPLES))
 --more--
```

I also find that if I run a sample directly, before doing anything else, then it hangs indefinitely until I interrupt it and kill the thread. For example, if I run `(cl-glut-examples:rb-cube)` before `(cl-glut-examples:run-examples)` then it will hang. But I reverse that order then `(cl-glut-examples:rb-cube)` will run fine.

I suspect that I might I have a version mismatch problem somewhere or perhaps some other configuration issue. Has anyone experienced anything else like this before?

Not sure if it is related, but if I run the `(sdl2-examples:basic-test)` before `(cl-glut-examples:run-examples)` then I get the same hanging behaviour. Since `sdl2` depends on `cl-opengl` I thought I would ask here first about that issue.

**Comment by marzipankaiser** [comment] 2015-01-25 16:38
Do your GPU & driver support OpenGL >=3.30 ?
I had a similar error when I tried to run the shader-vao example using my Intel GPU (that only supports OpenGL 2.1). [Those errors with INVALID-VALUE and INVALID-OPERATION]
Obviously, you can't use OpenGL 3.3 features if they aren't supported... (and shader-vao uses GLSL 3.30 which comes with OpenGL 3.3)

**Comment by ezrarush** [comment] 2015-01-25 18:20
the hanging might just be the hidden window "feature" of slime.  Refer to your old issue (https://github.com/lispgames/cl-sdl2/issues/23) and read the last few post.

**Comment by 3b** [comment] 2023-12-17 04:10
Split various things mentioned here into separate bugs and closing this one
* #106 for `116 is not defined as a value for enum type #<FOREIGN-ENUM CL-GLUT:SPECIAL-KEYS>.`
    freeglut added some special keys (left alt in this case) cl-glut didn't know about, but should soon
* #109 for `fghInitialize: CreateDC failed, Screen size info may be incorrect`
    emacs does odd things, which confuses freeglut, and probably caused most of the remaining problems. Possible workaround in #109, not sure if cl-glut can fix it portably easily or not.
* #110 for other possibility of first window just not showing up (though it sounds like that wasn't the only problem)
    caused by windows oddities, workaround in #110.

**Closed by 3b** 2023-12-17 04:10 UTC
